<?php

// This file is automatically generated by Laravel...

return [
    App\Providers\AppServiceProvider::class,
    \Valery\Installer\Providers\MainServiceProvider::class,
    Valery\Core\Providers\CoreServiceProvider::class,
];
